Repository gabdiniz/bibliotech, pull requests merged in 2023-04, with the labels that each got.

#36 Área de listagem de blogs
  src/App.jsx
  src/components/Menu/Menu.jsx
  src/firebase/collections.js
  src/firebase/postagens.js
  src/pages/AdicionarPostagem/AdicionarPostagem.jsx
  src/pages/Login/Login.jsx
  src/pages/Postagens/Postagens.css
  src/pages/Postagens/Postagens.jsx
Labels: documentation, enhancement

#46 Esquematização de mensagens de erro#39
  src/firebase/erros.js
  src/pages/AdicionarEmprestimo/AdicionarEmprestimo.jsx
  src/pages/AdicionarLivro/AdicionarLivro.jsx
  src/pages/AdicionarPostagem/AdicionarPostagem.jsx
  src/pages/Cadastro/Cadastro.jsx
  src/pages/EditarEmprestimo/EditarEmprestimo.jsx
  src/pages/EditarLivro/EditarLivro.jsx
  src/pages/Login/Login.jsx
  src/pages/NotFound/NotFound.jsx
  src/pages/Perfil/Perfil.jsx
Labels: documentation, enhancement

#47 Espelhamento de dados entre Authentication x Firestore
  src/App.jsx
  src/firebase/collections.js
  src/firebase/usuarios.js
Labels: documentation, enhancement

#48 Quiz de múltiplas questões
  src/App.jsx
  src/assets/icons/interrogacao.png
  src/components/Menu/Menu.jsx
  src/data/questoes.js
  src/pages/Cadastro/Cadastro.jsx
  src/pages/Login/Login.jsx
  src/pages/Quiz/Quiz.css
  src/pages/Quiz/Quiz.jsx
Labels: documentation, enhancement

#50 Recurso de esqueci minha senha
  src/App.jsx
  src/firebase/auth.js
  src/pages/Login/Login.jsx
  src/pages/RecuperarSenha/RecuperarSenha.css
  src/pages/RecuperarSenha/RecuperarSenha.jsx
Labels: documentation, enhancement

#56 Múltiplas categorias para Livro
  src/firebase/CategoriaLivros.js
  src/pages/AdicionarLivro/AdicionarLivro.jsx
  src/pages/EditarLivro/EditarLivro.jsx
  src/pages/Perfil/Perfil.jsx
Labels: documentation, enhancement

#58 Data de entrega dos livros emprestados
  src/firebase/emprestimos.js
  src/pages/AdicionarEmprestimo/AdicionarEmprestimo.jsx
  src/pages/Emprestimos/Emprestimos.jsx
Labels: documentation, enhancement

#60 Página de detalhe do livro
  src/App.jsx
  src/pages/AdicionarLivro/AdicionarLivro.jsx
  src/pages/AdicionarPostagem/AdicionarPostagem.jsx
  src/pages/DetalhesLivro/DetalhesLivro.css
  src/pages/DetalhesLivro/DetalhesLivro.jsx
  src/pages/EditarLivro/EditarLivro.jsx
  src/pages/Livros/Livros.jsx
  src/pages/Postagens/Postagens.css
  src/pages/Postagens/Postagens.jsx
Labels: documentation, enhancement

#62 Arrumar bug em Livros.jsx
  src/App.jsx
  src/pages/AdicionarLivro/AdicionarLivro.jsx
  src/pages/EditarLivro/EditarLivro.jsx
  src/pages/Livros/Livros.jsx
  src/pages/Quiz/Quiz.jsx
Labels: documentation

#66 Implementar conteúdos da Home
  src/firebase/usuarios.js
  src/pages/Home/Home.css
  src/pages/Home/Home.jsx
  src/pages/Login/Login.jsx
  src/pages/Perfil/Perfil.jsx
Labels: documentation, enhancement

#67 Página de Políticas de Privacidade
  package-lock.json
  package.json
  src/App.jsx
  src/components/Menu/Menu.jsx
  src/contexts/AuthContext.js
  src/firebase/collections.js
  src/pages/Footer/Footer.jsx
  src/pages/PoliticasPrivacidade/PoliticasPrivacidade.css
  src/pages/PoliticasPrivacidade/PoliticasPrivacidade.jsx
Labels: documentation, enhancement

#68 Área de autores
  src/App.jsx
  src/firebase/CategoriaLivros.js
  src/firebase/autores.js
  src/firebase/collections.js
  src/firebase/config.js
  src/pages/AdicionarAutor/AdicionarAutor.jsx
  src/pages/Home/Home.css
  src/pages/Home/Home.jsx
Labels: documentation, enhancement

#70 Bate-papo entre usuários da aplicação
  src/App.jsx
  src/components/Menu/Menu.jsx
  src/firebase/collections.js
  src/firebase/mensagens.js
  src/pages/Chat/Chat.css
  src/pages/Chat/Chat.jsx
Labels: documentation, enhancement

#71 Concertar erros na home
  src/App.jsx
  src/components/Menu/Menu.jsx
  src/pages/Home/Home.jsx
Labels: bug

#72 Correção bug chat firebase
  src/firebase/config.js
  src/pages/Chat/Chat.jsx
Labels: bug

#75 Relacionar livros e autores
  src/pages/AdicionarLivro/AdicionarLivro.jsx
  src/pages/EditarLivro/EditarLivro.jsx
  src/pages/Home/Home.css
  src/pages/Home/Home.jsx
Labels: documentation, enhancement

#76 add Tema escuro
  src/App.jsx
  src/components/Menu/Menu.jsx
  src/contexts/AuthContext.js
  src/contexts/ThemeContext.js
  src/pages/Emprestimos/Emprestimos.jsx
  src/pages/Footer/Footer.jsx
  src/pages/Home/Home.jsx
  src/pages/Livros/Livros.jsx
  src/pages/PaginaAjuda/PaginaAjuda.jsx
  src/pages/Perfil/Perfil.css
  src/pages/Perfil/Perfil.jsx
  src/pages/Postagens/Postagens.jsx
  src/pages/Root/Root.jsx
Labels: documentation, enhancement

#78 Comentar chat
  src/components/Menu/Menu.jsx
  src/pages/Chat/Chat.css
  src/pages/Chat/Chat.jsx
  src/pages/NotFound/NotFound.css
Labels: bug
